name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for JavaScript)
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Adjust the version as needed

      - name: Install dependencies
        run: npm ci  # For JavaScript projects

      - name: Run Security Scan
        run: npx snyk test  # For JavaScript, replace with appropriate command for other languages
